version: '3.6'

services:
    mongodb-test:
        image: mongo:4.4.11
        restart: "no"
        ports:
            - 27017:27017

        environment:
            MONGO_INITDB_ROOT_USERNAME: citizix
            MONGO_INITDB_ROOT_PASSWORD: S3cret
